-- AlterTable
ALTER TABLE `Camera` ADD COLUMN `detectedCapabilities` JSON NULL;

-- AlterTable
ALTER TABLE `CameraCatalogCapability` MODIFY `support` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';

-- AlterTable
ALTER TABLE `CameraCatalogProtocol` MODIFY `support` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `portConfigurable` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `authenticationRequired` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `onvifPtz` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `onvifDiscovery` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `onvifEvents` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';

-- AlterTable
ALTER TABLE `CameraCatalogProvisioning` MODIFY `support` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';

-- AlterTable
ALTER TABLE `CameraCatalogVariant` ADD COLUMN `qrProfile` ENUM('NONE', 'VIGION', 'MANUFACTURER_SERIAL', 'MANUFACTURER_UID', 'MANUFACTURER_TOKEN', 'MANUFACTURER_PROPRIETARY', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `qrPresent` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `qrContainsUid` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `qrContainsSerial` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `qrContainsMac` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `qrContainsWifi` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `qrProprietary` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `qrUsableByVigion` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `manufacturerAppRequired` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `manufacturerCloudRequired` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    MODIFY `localOperation` ENUM('SUPPORTED', 'UNSUPPORTED', 'CONDITIONAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';

-- Preserve uncertainty that the initial matrix explicitly marked as conditional.
UPDATE `CameraCatalogProtocol` p
JOIN `CameraCatalogVariant` v ON v.`id` = p.`variantId`
JOIN `CameraCatalogModel` m ON m.`id` = v.`modelId`
JOIN `CameraCatalogBrand` b ON b.`id` = m.`brandId`
SET p.`support` = 'CONDITIONAL'
WHERE p.`support` = 'UNKNOWN'
  AND (b.`normalizedName` = 'reolink' OR (b.`normalizedName` = 'mibo' AND p.`protocol` = 'ONVIF'));

UPDATE `CameraCatalogVariant`
SET `qrProfile` = 'MANUFACTURER_PROPRIETARY'
WHERE `qrProprietary` = 'SUPPORTED' AND `qrProfile` = 'UNKNOWN';
