-- Prompt 6/7: current operational health snapshot without heartbeat history explosion.
ALTER TABLE `GatewayCommand`
  MODIFY `type` ENUM(
    'GET_CAMERA_STATUS', 'TEST_CAMERA', 'START_STREAM', 'STOP_STREAM', 'STREAM_STATUS',
    'CAPTURE_SNAPSHOT', 'START_RECORDING', 'STOP_RECORDING',
    'CAMERA_DISCOVERY_START', 'CAMERA_DISCOVERY_CANCEL',
    'CAMERA_VERIFICATION_START', 'CAMERA_VERIFICATION_CANCEL', 'CAMERA_REGISTER',
    'CAMERA_HEALTH_CHECK', 'CAMERA_UNREGISTER'
  ) NOT NULL;

ALTER TABLE `Camera`
  MODIFY `connectionStatus` ENUM('UNKNOWN','CONNECTING','ONLINE','DEGRADED','OFFLINE','AUTHENTICATION_ERROR','UNSUPPORTED','ERROR') NOT NULL DEFAULT 'UNKNOWN',
  ADD COLUMN `lastHealthCheckAt` DATETIME(3) NULL,
  ADD COLUMN `lastSuccessfulHealthCheckAt` DATETIME(3) NULL,
  ADD COLUMN `consecutiveFailures` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `healthSequence` BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN `healthGeneration` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `healthFailureCode` VARCHAR(64) NULL,
  ADD COLUMN `healthProfile` JSON NULL,
  ADD COLUMN `currentNetworkAddress` VARCHAR(45) NULL,
  ADD COLUMN `currentServicePort` INTEGER NULL;
